apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      initContainers:
        - name: init-storage
          image: ghcr.io/sophy/php-fpm-todo:latest
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /var/www/storage/framework/cache
              mkdir -p /var/www/storage/framework/views
              mkdir -p /var/www/storage/framework/sessions
              chmod -R 777 /var/www/storage
              chmod -R 777 /var/www/database/database.sqlite
          volumeMounts:
            - name: storage-volume
              mountPath: /var/www/storage
      containers:
        - name: fpm
          image: ghcr.io/sophy/php-fpm-todo:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: storage-volume
              mountPath: /var/www/storage
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    php artisan config:clear
                    php artisan cache:clear
                    php artisan view:clear
                    php artisan route:clear
                    php artisan storage:link || echo "Storage link already exists"
                    chmod -R 777 /var/www/database/database.sqlite
        - name: nginx
          image: ghcr.io/sophy/nginx-php-fpm-todo:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
            - name: storage-volume
              mountPath: /var/www/storage
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: storage-volume
          persistentVolumeClaim:
            claimName: todo-storage-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |-
    server {
        listen       8088;
        server_name  _;

        root /srv/www/public;
        index index.html index.php;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        location ~ \.php$ {
            include fastcgi.conf;
            fastcgi_index index.php;
            fastcgi_pass localhost:9000;
        }

        location ~ /\.ht {
            deny all;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: todo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
