apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-k8s-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-db"  # This must match your PostgreSQL service name
  DB_PORT: "5432"
  DB_DATABASE: "laravel_db"
  DB_USERNAME: "laravel_user"
