apiVersion: v1
kind: Service
metadata:
  name: laravel-app
spec:
  selector:
    app: laravel-k8s  # Matches the label of the Laravel deployment
  ports:
    - protocol: TCP
      port: 9000         # Exposes port 9000 for PHP-FPM
      targetPort: 9000   # Points to the same port as the container
