apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-k8s
  labels:
    app: nginx-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-k8s
  template:
    metadata:
      labels:
        app: nginx-k8s
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-k8s-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: storage
              mountPath: /var/www/html/storage
      volumes:
        - name: nginx-k8s-config
          configMap:
            name: nginx-k8s-config  # Referencing the nginx ConfigMap
        - name: storage
          persistentVolumeClaim:
            claimName: laravel-k8s-storage-pvc
