apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-service
spec:
  selector:
    app: nginx-k8s  # Updated to match the deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
