apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-service
spec:
  selector:
    app: nginx-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Choose a port on your node
  type: NodePort  # Change from LoadBalancer to NodePort
