apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-k8s-deploy
  labels:
    app: postgres-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-k8s
  template:
    metadata:
      labels:
        app: postgres-k8s
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "laravel_db"
            - name: POSTGRES_USER
              value: "laravel_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-k8s-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-k8s-storage
          persistentVolumeClaim:
            claimName: postgres-k8s-pvc
