apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-k8s-pvc  # Matches the name used in postgres-deployment.yml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Increased for PostgreSQL performance

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-k8s-storage-pvc  # Matches the name used in nginx-deployment.yml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Increased for Laravel storage requirements
